### ISSUE TITLE
glc clean panics if lambda function does not exist

### ISSUE THREAD

**Issue by dbg-petrkutalek** [karl-cardenas-coding/go-lambda-cleanup#79]
**Describe the bug**
`glc clean` panics with segment fault if the lambda function name provided in the file does not exist in the AWS environment

**To Reproduce**
```
glc clean --region eu-central-1 -c 3 -l lambda-list.yaml -v -m -d
```
where `lambda-list.yaml` is as follows (the name of the function is a random one):
```
lambdas:
  - vyletela-holubicka-ze-skaly
```

**Expected behavior**
The error state should be handled and `glc` should exit in clean way.

**Desktop (please complete the following information):**
 - PRETTY_NAME="Ubuntu 22.04.2 LTS"
 - NAME="Ubuntu"
 - VERSION_ID="22.04"
 - VERSION="22.04.2 LTS (Jammy Jellyfish)"

**Additional context**
```
INFO[04/19/23] ******** DRY RUN MODE ENABLED ********       
INFO[04/19/23] ******** CUSTOM LAMBDA LIST PROVIDED ******** 
INFO[04/19/23] Scanning AWS environment in eu-central-1     
SDK 2023/04/19 15:02:19 DEBUG Request
GET /2015-03-31/functions/vyletela-holubicka-ze-skaly HTTP/1.1
Host: lambda.eu-central-1.amazonaws.com
User-Agent: aws-sdk-go-v2/1.17.6 os/linux lang/go/1.20.2 md/GOOS/linux md/GOARCH/amd64 api/lambda/1.30.1 go-lambda-cleanup/v2.0.5
Amz-Sdk-Invocation-Id: <REDACTED>
Amz-Sdk-Request: attempt=1; max=3
Authorization: AWS4-HMAC-SHA256 Credential=<REDACTED>, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-date;x-amz-security-token, Signature=<REDACTED>
X-Amz-Date: 20230419T130219Z
X-Amz-Security-Token: <REDACTED>
Accept-Encoding: gzip

SDK 2023/04/19 15:02:19 DEBUG request failed with unretryable error https response error StatusCode: 404, RequestID: <REDACTED>, ResourceNotFoundException: Function not found: arn:aws:lambda:eu-central-1:<REDACTED>:function:vyletela-holubicka-ze-skaly
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x96bdf6]

goroutine 1 [running]:
github.com/karl-cardenas-coding/go-lambda-cleanup/cmd.getAllLambdas({0xb5f848, 0xc00003a118}, 0xc0001d0ce0?, {0xc000091cf0?, 0x1, 0x0?})
        /home/runner/work/go-lambda-cleanup/go-lambda-cleanup/cmd/clean.go:425 +0x476
github.com/karl-cardenas-coding/go-lambda-cleanup/cmd.executeClean(0xc0001ff890)
        /home/runner/work/go-lambda-cleanup/go-lambda-cleanup/cmd/clean.go:144 +0xec
github.com/karl-cardenas-coding/go-lambda-cleanup/cmd.glob..func1(0xea7400?, {0xa7ead2?, 0x9?, 0x9?})
        /home/runner/work/go-lambda-cleanup/go-lambda-cleanup/cmd/clean.go:124 +0xa53
github.com/spf13/cobra.(*Command).execute(0xea7400, {0xc0000f01b0, 0x9, 0x9})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xea76e0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/karl-cardenas-coding/go-lambda-cleanup/cmd.Execute()
        /home/runner/work/go-lambda-cleanup/go-lambda-cleanup/cmd/root.go:100 +0x35
main.main()
        /home/runner/work/go-lambda-cleanup/go-lambda-cleanup/main.go:8 +0x17
```

**Comment by karl-cardenas-coding** [comment]
Thank you for reporting this @dbg-petrkutalek and for the kind note. I'll have a fix by the end of the week 🤙
